server:
  port: 2002
spring:
  application:
    name: seata-storage-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_storage
    username: root
    password: frsoft
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    # 自定义事务组名称需要与seata-server中的对应
#    alibaba:
#      seata:
#        tx-service-group: default

# seata配置
seata:
  # 此处的名称一定要与vgroupMapping下配置的参数保持一致
  tx-service-group: default
  service:
    disable-global-transaction: false
    # seata 地址配置，此处可以集群配置，是个数组
    grouplist:
      default: localhost:8091
    vgroupMapping:
      default: default

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'
